@HostAddress=https://localhost:7043/api

### V1 products
GET {{HostAddress}}/v1/products

### V1 product
GET {{HostAddress}}/v1/products/83878326-ae30-43e0-aa64-e2721aa9cb16

### V2 product
GET {{HostAddress}}/v2/products/13c55cff-fc46-46ea-9bd1-7c5352610b2a
