@HostAddress=https://localhost:7043/api

### V1 products
GET {{HostAddress}}/v1/products

### V1 product
GET {{HostAddress}}/v1/products/5f2d5b4c-3cc4-417b-99e6-8ded626e9538

### V2 product
GET {{HostAddress}}/v2/products/d6a20469-d656-404f-bf61-997cf52065a8
